spring.application.name=sipm

spring.datasource.url=jdbc:postgresql://localhost:5432/sipm
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


firebase.apiKey=AIzaSyAwrV9_nE0My-0YfSLSOio84w3QN2mWhLc
firebase.authDomain=sipm-87d88.firebaseapp.com
firebase.projectId=sipm-87d88
firebase.storageBucket=sipm-87d88.firebasestorage.app
firebase.messagingSenderId=230624667559
firebase.appId=1:230624667559:web:79aa7c7f76d62621a87882
firebase.measurementId=G-B3W0ZFGLDQ